```{r setup, include=FALSE}
library(ggplot2)
library(dplyr)
library(tidyverse)

data <- read.csv("V3 Merged Files Through 4-3 CLEANED.csv") %>% select(Date, PitcherId, PitcherThrows, BatterId, BatterSide, KorBB, PlayResult, PitchCall, AutoHitType, HitType, OutsOnPlay, RunsScored, ExitSpeed, Angle, Direction, Distance, Barrel, Strikes)

filtered_data <- data %>%
  filter((PitchCall == "InPlay" & (!is.na(ExitSpeed) | !is.na(Angle))) | PlayResult=="Undefined")
```

```{r}
#constants from FanGraphs
constants <- data.frame(
  constant = c("1B", "2B", "3B", "HR", "HBP", "UBB"),
  values = c(0, 0, 0, 0, 0, 0) 
  )

constants[1, "values"] <- .89
constants[2, "values"] <- 1.27
constants[3, "values"] <- 1.62
constants[4, "values"] <- 2.1
constants[5, "values"] <- .72
constants[6, "values"] <- .69

constants[,"values", drop=FALSE]
```

```{r}
#this is how we decided to split the EV and LA. Adjust appropriately for data size
ev_groups <- seq(0, 120, by = 5)  
la_groups <- seq(-90, 90, by = 2) 

#final xwOBA matrix
xwOBA_matrix <- matrix(0, nrow = length(ev_groups) - 1, ncol = length(la_groups) - 1)
colnames(xwOBA_matrix) <- paste("LA", head(la_groups, -1), "to", tail(la_groups, -1), sep = "_")
rownames(xwOBA_matrix) <- paste("EV", head(ev_groups, -1), "to", tail(ev_groups, -1), sep = "_")

#keep track of the count for each grouping
count_matrix <- matrix(0, nrow = length(ev_groups) - 1, ncol = length(la_groups) - 1)
colnames(count_matrix) <- paste("LA", head(la_groups, -1), "to", tail(la_groups, -1), sep = "_")
rownames(count_matrix) <- paste("EV", head(ev_groups, -1), "to", tail(ev_groups, -1), sep = "_")
```

```{r}
for (i in 1:(nrow(filtered_data))) {
  row_data <- filtered_data[i, ]
  
  #reset the hit type counts every iteration
  count_1B <- 0
  count_2B <- 0
  count_3B <- 0
  count_HR <- 0
  count_BB <- 0
  count_OUT <- 0
  
  if(row_data$KorBB == "Walk"){ #if it is a Walk then do not try to get EV and LA
    count_BB = 1
  } else if(!is.na(row_data$ExitSpeed) && !is.na(row_data$Angle)){ #if both EV and LA are not NA
    ev <- row_data$ExitSpeed
    la <- row_data$Angle
    
    #find the grouping for each EV and LA. Need the indices to be initialized outside of for loop
    ev_index <- 1
    la_index <- 1
    for(ev_index in 1:length(ev_groups) - 1){
      if(ev >= ev_groups[ev_index] && ev < ev_groups[ev_index+1]){
        break
      }
    }
    for(la_index in 1:length(la_groups) - 1){
      if(la >= la_groups[la_index] && la < la_groups[la_index+1]){
        break
      }
    }
    
    #mark hit type
    result = row_data$PlayResult
    if (result == "Single") {
      count_1B <- 1
    } else if (result == "Double") {
      count_2B <- 1
    } else if (result == "Triple") {
      count_3B <- 1
    } else if (result == "HomeRun") {
      count_HR <- 1
    } else{ 
      count_OUT <- 1
    }
  } else { #if it is not a walk and either EV or LA are NA go to the next row
    next
  }
  
    
    wOBA <- (count_1B * constants[1, "values"]) + (count_2B * constants[2, "values"]) + 
            (count_3B * constants[3, "values"]) + (count_HR * constants[4, "values"]) + (count_BB * constants[6, "values"])
    #should also incorporate HBP
    
    #add wOBA to the xwOBA matrix
    if(count_matrix[ev_index, la_index] == 0){ #if it is the first time then just insert the wOBA in the corresponding grouping in the matrix
      xwOBA_matrix[ev_index, la_index] <- wOBA
    } else { #otherwise recalculate the averages with this new wOBA
      prevAvg = xwOBA_matrix[ev_index, la_index]
      xwOBA_matrix[ev_index, la_index] = (wOBA + (prevAvg * count_matrix[ev_index, la_index]))/(count_matrix[ev_index, la_index] + 1)
    }
      
    count_matrix[ev_index, la_index] = count_matrix[ev_index, la_index] + 1
    
  #Note: No value in the xwOBA matrix should be greater than 2.1 (the HR constant) or less than 0
}
```
    
  count_matrix[ev_index, la_index] = count_matrix[ev_index, la_index] + 1

}
```
